[project]
name = "deep-research-agent"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "tavily-python",
    "pydantic",
    "pydantic-settings"
]
